### ISSUE TITLE
Nextcloud is not able to automatically generate favicons

### ISSUE THREAD

**Issue by davidv92** [Wonderfall/docker-nextcloud#11]
It seams `PHP module imagick` and/or `SVG support for imagick` (e.g. libmagickcore5-extra) are missing.

These modules are needed according to [Nextcloud documentation](https://docs.nextcloud.com/server/13/admin_manual/configuration_server/theming.html#theming-of-icons)

**Comment by benyanke** [comment]
Hi @davidv92 - this repo appears to be unmaintained, but feel free to try my fork, and if the issue still presents itself, open a ticket on my fork (gh: benyanke/docker-nextcloud), dh: benyanke/nextcloud) and I'll be happy to take a look and get this resolved.

**Comment by davidv92** [comment]
A new feature is available in Nextcloud 14. We can now directly select the file that will be used as favicon. In Administration/Theming Menu.
