### ISSUE TITLE
PHP Version in Nextcloud 13 Dockerfile breaks mcrypt

### ISSUE THREAD

**Issue by ghost** [Wonderfall/docker-nextcloud#13]
Hi, the mcrypt module got removed in PHP 7.2 and the saml plugin breaks because of this.
Maybe downgrade to PHP 7.1?

Also https://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt but this isn't your job :)

**Comment by bernerha** [comment]
They're know the problem https://github.com/nextcloud/user_saml/issues/168
