### ISSUE TITLE
Stable release gives code signin warning

### ISSUE THREAD

**Issue by etique57** [Wonderfall/docker-nextcloud#19]
Hello,

With the current stable release of the docker image, I get the following warning:
`Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation.`

Is it intended/inevitable?

Cheers!

**Comment by benyanke** [comment]
Hi @etique57 - this repo is unmaintained, but feel free to open a ticket on my fork (gh: benyanke/docker-nextcloud), dh: benyanke/nextcloud) and I'll be happy to take a look and get this resolved.

**Comment by etique57** [comment]
thanks @benyanke can I just change the image in my docker-compose, and restart it?

**Comment by benyanke** [comment]
Yup - I've built it to pick up directly from this one, so it should be seamless.

**Comment by etique57** [comment]
Ok, giving it a try, I'll log an issue if the problem is still here.

Cheers!

**Comment by benyanke** [comment]
Great - if it still is, please open a ticket on my repo!
