### ISSUE TITLE
[Suggestion] Allow us to SSH into the container

### ISSUE THREAD

**Issue by ProPublic1110** [Wonderfall/docker-nextcloud#23]
Currently, if we try to SSH into the container via docker exec, we get this:

`
(user)@(server):~/folder1$ docker exec -i -t (container id) bash
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
`

**Comment by Wonderfall** [comment]
*(This is not SSH, you just want to open a shell in the container.)*

Your command does not work since this image does not have `bash` installed.
Juste use `sh` instead : `docker exec -ti container_name sh`.

**Comment by ProPublic1110** [comment]
Ahh thanks
