### ISSUE TITLE
Long Startup Time, /nextcloud Permissions

### ISSUE THREAD

**Issue by PhasecoreX** [Wonderfall/docker-nextcloud#25]
This is kind of like #14, but specifically for the /nextcloud folder. I don't have issues with permissions in my /data folder (yet...)

Every time I recreate my Nextcloud container, it goes through the process of making sure all permissions are correct for a bunch of folders. This is great and all, except that when it processes the /nextcloud folder, it always needs to correct the permissions. Since this is such a large directory, it takes several minutes (of downtime and disk thrashing) to process.

Doing a bit of research, it looks like the user and group of these files is "nobody" and "nogroup", respectively. This probably comes from building the docker file when the whole thing is un-tarred.

Does this folder need to have its permissions changed to still function? I like permission checking/resetting, but I also like my disks to not die doing the same chown task over and over.

**Comment by steffen201706** [comment]
is this an option to put the update in background 

chown -R $UID:$GID $dir &

**Comment by benyanke** [comment]
@steffen201706 

This is likely to cause intermittent issues on startup. If the permissions aren't finished setting before the user is able to access the app, why set them in the first place? I'd rather have an app be offline than be broken and then fix itself later.

**Comment by benyanke** [comment]
@PhasecoreX This has been implemented as optional in my fork via env var `PERMISSION_RESET`.

https://github.com/benyanke/docker-nextcloud/

**Comment by steffen201706** [comment]
PERMISSION_RESET is a good idea 
options: alway, never, background :-)

**Comment by Wonderfall** [comment]
Sorry I didn't get in touch in time. Support for legacy images has ended since they're now obsolete: consider using the new image instead or the official image. Have a nice day!

(As for your issue, it's a known one due to terrible chown performance on the overlay2 storage driver used by default in Docker. The new image doesn't enforce that anymore.)
