### ISSUE TITLE
nginx.conf inside a volume

### ISSUE THREAD

**Issue by suprovsky** [Wonderfall/docker-nextcloud#26]
Hey, is that possible to link /nginx/sites-enabled/nginx.conf to the volume? It would be much easier to set up HTTPS connection as every update would erase changes in this particular file.
Since I'm a Docker newbie, is there any alternative to set up and store nginx configuration unchanged between updates? I wanted to make sure I don't ask for something useless.

supra

**Comment by rgarcia89** [comment]
-v locationOnYourHost:/nginx/sites-enabled/nginx.conf

**Comment by suprovsky** [comment]
Thanks for help. Please close this issue.
