### ISSUE TITLE
Nginx SSL support

### ISSUE THREAD

**Issue by suprovsky** [Wonderfall/docker-nextcloud#27]
Hey, it seems Nginx doesn't support SSL as ssl module wasn't compiled during image creation.
I set up nginx.conf config file in the way below:
https://gist.github.com/suprovsky/c321e4e7736c6fc11e0851b6b00792d8

Before applying configuration I wanted to check whether is correct and I got the error:
```
/ # nginx -t
nginx: [emerg] the "ssl" parameter requires ngx_http_ssl_module in /nginx/sites-enabled/nginx.conf:3
nginx: configuration file /nginx/conf/nginx.conf test failed
```
Nginx [documentation](http://nginx.org/en/docs/http/ngx_http_ssl_module.html) says this module *isn't* compiled by default. It requires __--with-http_ssl_module__ parameter to be used during nginx compilation.

**Comment by benyanke** [comment]
The image is designed to be used as a backend. You need to set up a separate proxy container to terminate TLS

**Comment by DanielYWoo** [comment]
This image is a backend container, you need your own edge/frontend container or even hardware load balancer to do SSL offload before this container.
