### ISSUE TITLE
Redis and SMTP Settings

### ISSUE THREAD

**Issue by umardraz** [Wonderfall/docker-nextcloud#29]
Hi,

I have already running my database and **redis** on separate servers, Now we can define the database variables while launching the container but what what is the environment variables for **redis** server? 

2nd I want to mention smtp settings as well, is there way that we can pass environment variable for smtp settings as well?

**Comment by benyanke** [comment]
Added two tickets for this, as you see above. I'll try and get these implemented in my fork.

This seems like a great idea.

**Comment by steffen201706** [comment]
small suggestion for the problems/wishes above
nextcloud supports multiple xxxx.config.php additional to the config.php

so i have created an email.config.php and put this in the nextcloud/config directory

<?php
$CONFIG = array (
  'mail_from_address' => 'nextcloud_staging',
  'mail_domain' => 'mydomain.de',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtphost' => '10.200.1.6',
  'mail_smtpport' => '25',
);

This values are in realtime "virtual added" to the config.php.
Same procedure with redis, db, preview, proxies, ....

For an easyer handling i have published the complete config directory in my docker-compose file.
