### ISSUE TITLE
Nextcloud 16 update

### ISSUE THREAD

**Issue by suprovsky** [Wonderfall/docker-nextcloud#50]
Hi there,

I wanted to notify you that there is an update for it, it's version 16 and their repo is here:
https://github.com/nextcloud/docker
If you'd let me know how to track changes between versions, I think if the version 17 will come in the future I could make a pull request next time.

I really appreciate your time in that project. Thanks!

**Comment by phiwey** [comment]
Hi,
it's looking like you have updated the Dockerfile on GitHub, but the linked Dockerfile on Docker Hub is still the one for version 15.0.5.
Could you please check this and update on Docker Hub also?
Thanks for you work!

**Comment by suprovsky** [comment]
Hi,

since Wonderfall is not responding, I've forked this repository and made the update by myself.
https://hub.docker.com/r/suprovsky/nextcloud

Thanks for doing a great repo Wonderfall!
