### ISSUE TITLE
Fix Urgent security issue in NGINX/php-fpm

### ISSUE THREAD

**Issue by davidv92** [Wonderfall/docker-nextcloud#59]
Please, could you update wonderfall/nextcloud image in order to fix that security issue : https://nextcloud.com/blog/urgent-security-issue-in-nginx-php-fpm/

Thanks.

**Comment by scrummie02** [comment]
According to the NGINX config recommendation that part is covered, the PHP needs to be updated.

**Comment by Wonderfall** [comment]
It is now fixed. Although I'd never advice to use my image as is (especially if you're relying on Docker Hub builds), you can only trust yourself (it's OK if it's a big image used by tons of people) in general. I forgot to push the changes and it's kinda my fault, I don't realise my images are being used by other people.

If it were to happen again, don't hesitate to fork / make the changes yourself! I can be very busy for months so no guarantees I can update this repo frequently.
