### ISSUE TITLE
latest release OCI runtime exec failed

### ISSUE THREAD

**Issue by blarg3891** [Wonderfall/docker-nextcloud#69]
My container instance is in some failed state after what i believe was the latest update.
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

I installed a new blank instance with same docker-compose that has always worked fine and I was able to complete the nextcloud install.  It looked like it was working but after I restarted the container, I got the same error.

Never had issue before not sure what has changed.  I"m still trying to figure it out.  Any help would be greatly appreciated.

**Comment by rgarcia89** [comment]
@blarg3891 I am seeing the same issue...
Have you already figured out the issue?

**Comment by blarg3891** [comment]
> @blarg3891 I am seeing the same entry in my logs...
> Have you already figured out the issue?

Nope...

**Comment by Wonderfall** [comment]
https://github.com/Wonderfall/docker-nextcloud/commit/7039f3bfc67c9fbd617e69256fdaf586c276cfa3 should fix it.
Gonna push the 20 update once I tried it.

**Comment by rgarcia89** [comment]
@Wonderfall way better :)
thanks

**Comment by Wonderfall** [comment]
Reverted back to PHP 7.4 with UID/GID workaround fix. Gonna keep this issue open until the issue is resolved upstream.
