### ISSUE TITLE
Update nginx version to 7.4.x

### ISSUE THREAD

**Issue by stp-bsh** [Wonderfall/docker-nextcloud#70]
The developer of the nextcloud app "Passwords" announced the EOL for the following:

- EOL warning for NC < 19
- EOL warning for PHP < 7.4

Please see https://git.mdns.eu/nextcloud/passwords/blob/master/CHANGELOG.md

Would it be feasible to update to nginx 7.4?

I tried to build my own image using your `wonderfall/nextcloud:7.4` image, but unfortunately this version is hanging for ever at `occ upgrade`.

**Comment by c0ryb4k3r** [comment]
I believe the occ hang is only if you specify a uid/gid that doesn't exist in the image. there is an open issue with the nextcloud repo.  creating a user with the required uid got me going again anyway.

**Comment by stp-bsh** [comment]
> I believe the occ hang is only if you specify a uid/gid that doesn't exist in the image. there is an open issue with the nextcloud repo. creating a user with the required uid got me going again anyway.

I'll give that a try :+1:

**Comment by stp-bsh** [comment]
Yes, you're right. Adding the missing uid/gid worked. It is now an ugly hardcoded hack in my local Dockerfile

```
RUN adduser -g 1000 --uid 1000 --system nextcloud \
 && apk -U upgrade \
```
but it works. Will see when the nextcloud issue will be fixed.
