### ISSUE TITLE
docker dont install

### ISSUE THREAD

**Issue by frezeen** [Wonderfall/docker-nextcloud#77]
Updating permissions...
Updating permissions in /nextcloud...
Updating permissions in /data...
Updating permissions in /config...
Permissions in /apps2 are correct.
Updating permissions in /var/log...
Updating permissions in /php...
Updating permissions in /nginx...
Updating permissions in /tmp...
Updating permissions in /etc/s6.d...
ne updating permissions.
Check for UserId 1000
Creating user nextcloud with UID=1000 and GID=1000
Starting automatic configuration...
Automatic configuration finished.

this is my log and stop here..  what im wrong?

my docker file
version: '3'

networks:
  nextcloud_network:
    external: false
services:
  nextcloud:
    image: wonderfall/nextcloud
    container_name: nextcloud
    depends_on:
      - nextcloud-db           # If using MySQL
      - redis                  # If using Redis
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Rome
      - DOMAIN=localhost
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=xxxxxxxx
      - DB_HOST=nextcloud-db
    volumes:
      - /mnt/Data/nextcloud:/data
      - /mnt/Config/nextcloud:/config
      - /mnt/Config/nextcloud/apps:/apps2
      - /mnt/Config/nextcloud/themes:/nextcloud/themes
    networks:
      - nextcloud_network

  # If using MySQL
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    volumes:
      - /mnt/Config/mariadb_nc:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=xxxxxxxxxx
    networks:
      - nextcloud_network

  # If using Redis
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /mnt/Config/redis:/data
    networks:
      - nextcloud_network

**Comment by Wonderfall** [comment]
Sorry I didn't get in touch in time. Support for legacy images has ended since they're now obsolete: consider using the new image instead or the official image. Have a nice day!

(As for your logs, they seem normal. More details would be needed.)
