### ISSUE TITLE
upgrade path versions older than nextcloud 19

### ISSUE THREAD

**Issue by utillich** [Wonderfall/docker-nextcloud#79]
Hello, 

I understand that only the newest versions are supported, however is there an upgrade path for anyone on an older version of the images? 

If I am not mistaken one should not skip versions, even if its only running the container once to update the data i.e. 16 -> 17 -> 18 -> 19 -> 20 -> 21 
Since there are no tags for anything lower than 20, how can older setups be updated?  

Any help would be much appreciated!

**Comment by Wonderfall** [comment]
Build arguments will be useful for that. To do son, first clone this repository, and then build the needed versions using `docker build`. For instance you could do that:

```
docker build -t wonderfall/nextcloud:19 -f Dockerfile.20 --build-arg NEXTCLOUD_VERSION=19.0.10 .
```
