### ISSUE TITLE
no smb?

### ISSUE THREAD

**Issue by DeAlexPesh** [Wonderfall/docker-nextcloud#84]
![image](https://user-images.githubusercontent.com/16735261/121535476-a5d41700-ca1b-11eb-954b-2e7610a47ae8.png)

**Comment by Wonderfall** [comment]
Hello,
As you can guess there's no samba client included since I wanted to keep the image minimal. That being said, you can still add the functionality yourself. This would be way to achieve that:

```
FROM ghcr.io/wonderfall/nextcloud:21

RUN apk -U add libsmbclient \
 && pecl install smbclient \
 && echo "extension=smbclient.so" > /usr/local/etc/php/conf.d/smbclient.ini
```

Hope this helps.

**Comment by polcape** [comment]
Sorry @Wonderfall, this command is valid also for version 22?

Can I use it in a docker-compose file? Where?

Thanks

**Comment by Wonderfall** [comment]
> Sorry @Wonderfall, this command is valid also for version 22?

Yes, of course! It's just a custom Dockerfile.

> Can I use it in a docker-compose file? Where?

You'll need to build your own image based on `ghcr.io/wonderfall/nextcloud:22`. In your docker-compose.yml, you can use `build: <PATH>` instead of `image: ghcr.io/wonderfall/nextcloud:22` where `<PATH>` is path to your own Dockerfile.

**Comment by polcape** [comment]
Thanks @Wonderfall I try, but on command
`pecl install smbclient`

this is the error

`Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

ERROR: `phpize' failed
ERROR: Service 'nextcloud' failed to build : The command '/bin/sh -c apk -U add libsmbclient  && pecl install smbclient  && echo "extension=smbclient.so" > /usr/local/etc/php/conf.d/smbclient.ini' returned a non-zero code: 1
`

**Comment by polcape** [comment]
Update: I solve with this Dockerfile

`FROM ghcr.io/wonderfall/nextcloud

USER root

RUN apk -U add libsmbclient samba-dev\
 && apk -U add autoconf gcc make g++ zlib-dev \
 && pecl install smbclient \
 && echo "extension=smbclient.so" > /usr/local/etc/php/conf.d/smbclient.ini
 
USER 1000`

**Comment by Wonderfall** [comment]
Yeah, privileges are needed to install additional packages.

**Comment by DeAlexPesh** [comment]
Dockerfile

```bash
FROM ghcr.io/wonderfall/nextcloud:latest

USER root

RUN apk add --no-cache libsmbclient samba-dev \
 && apk add --no-cache autoconf gcc make g++ zlib-dev \
 && pecl install smbclient \
 && echo "extension=smbclient.so" > /usr/local/etc/php/conf.d/smbclient.ini \
 && rm -rf /var/cache/apk/*

USER nextcloud
```
