### ISSUE TITLE
Missing FFMPEG

### ISSUE THREAD

**Issue by LynxPDA** [Wonderfall/docker-nextcloud#86]
In new docker image 21.0.3 ffmpeg is missing.
In config.php i have:

> 'enabledPreviewProviders' =>
  array (
    1 => 'OC\\Preview\\PDF',
    2 => 'OC\\Preview\\Image',
    3 => 'OC\\Preview\\Photoshop',
    4 => 'OC\\Preview\\TIFF',
    5 => 'OC\\Preview\\SVG',
    6 => 'OC\\Preview\\Movie',
    7 => 'OC\\Preview\\MKV',
    8 => 'OC\\Preview\\MP4',
    9 => 'OC\\Preview\\AVI',
  ),

And it had work properly. But after upgrade from 21.0.1 to 21.0.3 preview for video dosnt work.

**Comment by Wonderfall** [comment]
Hello, `ffmpeg` was indeed removed from the default packages. You can add it back like this:

```
FROM ghcr.io/wonderfall/nextcloud:21
RUN apk -U add ffmpeg
```

**Comment by LynxPDA** [comment]
I used
`docker exec -it --user root nextcloud apk -U add ffmpeg`
And it works great, thank you!
