### ISSUE TITLE
Recognize app dosnt work

### ISSUE THREAD

**Issue by LynxPDA** [Wonderfall/docker-nextcloud#87]
Hello!
In new image 21.0.3 when i am install [Recognize ](https://apps.nextcloud.com/apps/recognize) app from store - it dosnt work.

When i use

> docker exec -it nextcloud php occ recognize:classify

and i got

> Classifier process output: sh: exec: line 1: /nextcloud/apps2/recognize/bin/node-v14.9.0-linux-x64: not found

But file node-v14.9.0-linux-x64 really have been in /nextcloud/apps2/recognize/bin/

I think there may not be enough libraries.
Considering that Nextcloud is a good alternative to the now paid Google Photos, the functionality of the Recognize application can be very useful.

How can this problem be corrected?

**Comment by Wonderfall** [comment]
Hello, first thing that crossed my mind is that the bundled node binary is compiled for glibc systems. Alpine uses another C library, musl instead. Could you try swapping the binary in that folder with one you can get from [there](https://unofficial-builds.nodejs.org/download/release/v14.9.0/)?

**Comment by LynxPDA** [comment]
Yes, i did it and get:

> The current PHP memory limit is below the recommended value of 512MB.

and at finish

> Classifier process output: fatal allocator error: sized deallocation mismatch (small)
>
>Failed to classify images
>The process has been signaled with signal "6".

**Comment by Wonderfall** [comment]
Please use the `occ` command directly, not `php occ`. It’ll set a higher memory limit according to the `MEMORY_LIMIT` environment variable (which is, by default, 512MB).

**Comment by LynxPDA** [comment]
Done!

When i swapping the binary in that folder with one you can get from [there ](https://unofficial-builds.nodejs.org/download/release/v14.9.0/) and recreated a container with a blank LD_PRELOAD value 

> docker exec -it nextcloud php occ recognize:classify

Working right! Thanks a lot!

**Comment by GUNT0815** [comment]
> Done!
> 
> When i swapping the binary in that folder with one you can get from [there ](https://unofficial-builds.nodejs.org/download/release/v14.9.0/) and recreated a container with a blank LD_PRELOAD value
> 
> > docker exec -it nextcloud occ recognize:classify
> 
> Working right! Thanks a lot!

I tried to follow the solution here without success. Can you pls be so kind and give a more detailed explanation (newby-like), what has to be done, to get recognize working. So whicht exact file to copy where ... and which parameter to adjust in which file. Thank you
