### ISSUE TITLE
Nextcloud - trusted domain access

### ISSUE THREAD

**Issue by CyberHacky-zz** [Wonderfall/docker-nextcloud#88]
- how to allow all domains can access Nextcloud and remove the domain verification process,
- I want to upload this online server so my team can access docker from any machine and domain, so can you give me an idea about how can I add multiple domains or remove that functionally from nextcloud so any domain can access the docker homepage

**Comment by Wonderfall** [comment]
This is controlled by the `trusted_domains` in `config.php`. It should support `*` as a wildcard.
