### ISSUE TITLE
ENV Needed: DB_PORT

### ISSUE THREAD

**Issue by benyanke** [Wonderfall/docker-nextcloud#9]
Many times on a host with only one IP, the DB needs to run on a nonstandard port.

**Comment by Wonderfall** [comment]
Why don't you use DB_HOST ?

`Your host server name, for example localhost, hostname, hostname.example.com, or the IP address. To specify a port use hostname:####; to specify a Unix socket use localhost:/path/to/socket.`

**Comment by benyanke** [comment]
Thanks for the additional info - I'll text when I have a moment and get back with more details or close the ticket.

**Comment by benyanke** [comment]
I must have done something wrong when I tried it initially, because that worked for me.

Thanks again!
