### ISSUE TITLE
From  wonderfall/nextcloud migrate to ghcr.io/wonderfall/nextcloud:22  appear exception

### ISSUE THREAD

**Issue by xjl456852** [Wonderfall/docker-nextcloud#91]
From  wonderfall/nextcloud migrate to ghcr.io/wonderfall/nextcloud:22  appear exception

When I has edited the docker-compose.yml and start the docker, I visit to the nextcloud web, The nextcloud prompts me to update, When I click the update button, It shows me some exception.

Exception: Updates between multiple major versions and downgrades are unsupported.

my new docker-compose.yml

version: '3'

networks:
  nextcloud_network:
    external: false

services:
  nextcloud:
    image: ghcr.io/wonderfall/nextcloud:22
    depends_on:
      - nextcloud-db           # If using MySQL
      - redis                  # If using Redis
    environment:
      - UID=1000
      - GID=1000
      - UPLOAD_MAX_SIZE=10G
      - APC_SHM_SIZE=128M
      - OPCACHE_MEM_SIZE=128
      - CRON_PERIOD=15m
      - TZ=Europe/Berlin
      - DOMAIN=localhost
      - ADMIN_USER=xxx
      - ADMIN_PASSWORD=xxx
      - DB_TYPE=mysql
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASSWORD=xxx
      - DB_HOST=nextcloud-db
    volumes:
      - /data/nextcloud/html/data:/data
      - /data/nextcloud/html/config:/nextcloud/config
      - /data/nextcloud/html/apps:/nextcloud/apps2
      - /data/nextcloud/html/themes:/nextcloud/themes
    networks:
      - nextcloud_network
    ports:
      - 8888:8888

  nextcloud-db:
    image: mariadb
    volumes:
      - /data/mariadb/datadir:/var/lib/mysql
      - /data/mariadb/conf.d/:/etc/mysql/conf.d/
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=xxx
    networks:
      - nextcloud_network
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - /data/redis/data:/data
    networks:
      - nextcloud_network

**Comment by Wonderfall** [comment]
Sorry for the late answer.

> Exception: Updates between multiple major versions and downgrades are unsupported.

Is explicit. Only n+1 migrations are supported. Check your current installed version and build the necessary images: https://github.com/Wonderfall/docker-nextcloud/issues/79

It's a pain if you're late in major updates but there's no other way.
